### ISSUE TITLE
github version (1.1) is older than cran version (1.2)

### ISSUE THREAD

**Issue by jwang-lilly** [xinyue-L/PML#1]
Hi,  Thanks much for the package for Circadian Rhythm Analysis.  I just tried to run a few of your examples and encountered the following.  Is this intended?  I am using cran installation.

> #### directly display trelliscope panels, no dataset is returned
> tre(lis3,plot.ind=TRUE,plot.tre=TRUE,plot.tre.path = ".")
No trelliscope individual plots are generated due to the archived trelliscopejs package.

I also tried the older github version but it has a different error:
data(lis3)
pa3 <- form(lis3)
something like "activity length should be 1, not 13"

@xinyue-L

**Comment by xinyue-L** [comment]
Dear Jian,

Thank you again for using the package. This is strange as I just ran it using R 3.6.1 and did not encounter the problem on my end. How about directly using the pa3 data in the package? Activity length is of 13 in pa3.

Best regards,
Xinyue

**Comment by jwang-lilly** [comment]
Dear Xinyue,

Thanks much for your prompt response.  Yes, I did use the synthetic data comes with PML.

Is it possible for you to upload PML version 1.2 (the same version as cran) to github? 

Thanks,

**Comment by xinyue-L** [comment]
Dear Jian,

Thank you and I have uploaded the version 1.2 with descriptions on the request by CRAN to remove trelliscopejs related functions. Thank you!

Best,
Xinyue

**Comment by jwang-lilly** [comment]
Thanks much for uploading PML 1.2 to github.

I think you know this that the latest version of trelliscopejs (0.2.4, released in Feb. 10, 2020) works fine with PML 1.1.
